### ISSUE TITLE
Page management

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/lixilotus#17]
* One page can have many payment addresses
* User account is non-custodial
* User account can create multiple shop accounts
* Page account is custodial
* Page can be a hierarchy (branding, sub-store)
* Role/permission for accounts
* User account is custodial if user uses username/password instead of key (user need to keep recover phrase) (key can be encrypted with username/password) 
* Ability to transfer the page
* Ability to delegate permission to other accounts

Page info
* Name, address, phone, icon, handle, website, country, city, lotus address, mnemonic...

**Comment by nghiacc** [comment]
This will be tracked in smaller tickets
