### ISSUE TITLE
Comment to posts (L1)

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/lixilotus#21]
Use on change messages

- Comments is sorted from older (top) to newer (bottom)
- Show last 5 comments with a View previous comments link on the top (similar to MS Teams)
- Ability to filter comments based on Lotus burnt
- Comment box is at the bottom
- Comment button to quick link to the comment box

**Comment by nghiacc** [comment]
- Comments is sorted from older (top) to newer (bottom)
- Show last 5 comments with a View previous comments link on the top (similar to MS Teams)
- Ability to filter comments based on Lotus burnt
- Comment box is at the bottom
- Comment button to quick link to the comment box

**Comment by nghiacc** [comment]
Closing but need to fix the focus (desktop) and scrolling to the last comments.
