### ISSUE TITLE
Account sidebar to manage accounts

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/lixilotus#223]
![image](https://user-images.githubusercontent.com/236093/196072615-04bc7762-97d5-4878-ab55-caa95fdc9fb1.png)

**Comment by eric-son12** [comment]
![screencapture-lixilotus-test-wallet-2022-10-21-17_04_21](https://user-images.githubusercontent.com/48612433/197170658-fed502ba-433e-413d-8512-438739837429.png)
![screencapture-lixilotus-test-wallet-2022-10-21-17_04_07](https://user-images.githubusercontent.com/48612433/197170681-7485f5fb-1ccd-4f97-a501-bec3345866cc.png)
![screencapture-lixilotus-test-wallet-2022-10-21-17_03_51](https://user-images.githubusercontent.com/48612433/197170703-6d27e500-bda3-43ae-801e-4d7884ab7d59.png)

**Comment by eric-son12** [comment]
https://github.com/bcProFoundation/lixilotus/pull/236

pls check code!
