### ISSUE TITLE
Should change the post editor to upload images instead embedded images

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/lixilotus#255]
Currently when copy and paste to the editor, the images are pasted as base-64 string. It's big and exceed the limit of post graphql.
Solution:
* When copy and paste, only text are pasted
* The image need to be uploaded with the upload dialog

Reference: myriad.

**Comment by eric-son12** [comment]
https://github.com/bcProFoundation/lixilotus/pull/261
