### ISSUE TITLE
[Design] Need the design for the 404 not found page

### ISSUE THREAD

**Issue by vince8x** [bcProFoundation/lixilotus#259]

**Comment by Hongtta90** [comment]
**Figma link:**
https://www.figma.com/file/jZsKRAdU8umeMtINZQMCM5/LixiLotus-Love?node-id=1689%3A39062

**File of illustration**
![404](https://user-images.githubusercontent.com/104269464/200369918-9f2ea35a-10bd-4360-bccd-138ea98bd974.png)
