### ISSUE TITLE
QR Modal Flickering

### ISSUE THREAD

**Issue by KenNguyen-dev** [bcProFoundation/lixilotus#295]
When open QR Code Modal, it flickers every 5s

![LixiLotus - Google Chrome 2022-11-18 16-51-28](https://user-images.githubusercontent.com/74177525/202673654-46da4445-fb96-4e9b-b467-5b294aaaa1d9.gif)

**Comment by vince8x** [comment]
Consider to use dispatch openModal action to have multiple modal dialog stacked.
