### ISSUE TITLE
Correct the LL Logo (Currently > 90o)

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#315]
This logo angle looks more correct. 

![Image](https://user-images.githubusercontent.com/19528107/205211702-a74080bf-c587-4bad-853f-81687d00d2a9.png)

**Comment by Hongtta90** [comment]
LixiLotus Logo

![LL Logo](https://user-images.githubusercontent.com/104269464/205816719-59d35f1c-bc35-44d6-9346-58dacda0ecac.svg)
![LL Icon 48](https://user-images.githubusercontent.com/104269464/205816737-5be7696b-0729-4b0f-9c51-de3f9db40c07.svg)
