### ISSUE TITLE
Page Details Page (Basic)

### ISSUE THREAD

**Issue by thtung2901** [bcProFoundation/lixilotus#43]
- Users can view the details of companies here (Name, categories, description, address)

**Comment by nghiacc** [comment]
Finished basic function, the followings have not done:
- Lotus Credit Point is **Total Upvote XPI - Total DownVote XPI**.
- Users can upvote/downvote the company.
- Users can add comments for the company.
   - Users have to burn XPI (default 10 XPI, user can change it) to write a comment.
   - Users can upvote/downvote their and others' comments by burning XPI. (default 10 XPI, user can change it)
   - Comments that have the Lotus Credit Point under 0 will be hidden. (Need a checkbox to show/hide these comments)
