### ISSUE TITLE
Share link on Android show "Please input title"

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#630]
On Android, click on the Share button, the Please input title is showing... Need to fix

![Image](https://user-images.githubusercontent.com/19528107/235308924-f192be05-f852-491a-8a28-4757b59131a7.png)

It should shows the post owner and first characters of the post, similar to Twitter:
e.g. nghiacc on LixiLotus: There is no moderation in LixiLotus...
LixiLotus.com

**Comment by KenNguyen-dev** [comment]
![Image](https://github.com/bcProFoundation/lixilotus/assets/74177525/9764f144-f492-4420-be1a-442b036df616)
