### ISSUE TITLE
Show fees notice in the Custom burn dialog

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#667]
In this screen, need to show information about fees and tips:

Upvote/downvote in page:
You are burning 1 XPI.
You will send 0.04 XPI to page owner.
Miners' fees excluded.

Upvote/downvote in account:
You are burning 1 XPI.
You will send 0.08 XPI to account owner.
Miners' fees excluded.

(the message will need to be changed based on the fees and tips rules.

![Image](https://user-images.githubusercontent.com/19528107/238370425-bddfcd6c-65e5-4bc9-9916-04191db5aea0.png)

**Comment by nghiacc** [comment]
Need to notice on miners' fees too:
Miners' fees excluded.

**Comment by Huygon764** [comment]
Tested on dev environment @vince8x

**Comment by vince8x** [comment]
Missing the text: "Miners' fees excluded"

**Comment by vince8x** [comment]
Tested on production
