### ISSUE TITLE
Top Accounts panel is not showing the bottom part

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#757]
Steps:
1. Open LixiLotus.com, given the screen does not show all Top Accounts panel.
2. Scroll down a bit to see more on the top account.

![Image](https://user-images.githubusercontent.com/19528107/241118742-82699cc2-c198-487a-82b8-d6705f672e01.png)

**Comment by vince8x** [comment]
Deployed to production. a @nghiacc please help to test.
