### ISSUE TITLE
Limit the max level to 1000

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#771]
Currently the levels above 1000 is not legible. Can limit to 1000 for now. It is also high enough to worry about.
It also help to establish a community standard and perception around which posts are likely to go viral and proper moderation is needed when a post gather more than 1000 Lotus burned for it.

**Comment by Huygon764** [comment]
tested on dev environment @vince8x

**Comment by vince8x** [comment]
Tested on production.
