### ISSUE TITLE
Vietnamese translation correction for Top Accounts

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#789]
It should be "Xếp hạng tài khoản" , "đã đốt" need to be removed to be consistent with English version.

![Image](https://user-images.githubusercontent.com/19528107/242432962-e051fc97-e5d6-460f-a6cf-58d8605c1751.png)

**Comment by Huygon764** [comment]
tested on dev environtment @vince8x

**Comment by vince8x** [comment]
Tested on production environment
